stages:
  - build

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
    - npm run export
    - mv .next/static ./.next/static_tmp
    - mv .next/static_tmp/ _tmp
    - mv _tmp/* public/
    - rm -rf public/static_tmp _tmp
  artifacts:
    paths:
      - public
  only:
    - main